### ISSUE TITLE
关于如何在windows上运作zhongkui的问题

### ISSUE THREAD

**Issue by zzkzkkzzkk** [bukaleyang/zhongkui-waf#1]
我已下载openresty并且将zhongkui导入到openresty。
然后我将此项目安装在D盘。绝对路径为D:\openresty-1.21.4.1-win64\zhongkui-waf-master
接着我按照提示对配置文件做如下修改
lua_package_path "D:/openresty-1.21.4.1-win64/zhongkui-waf-master/?.lua;D:/openresty-1.21.4.1-win64/zhongkui-waf-master/lib/?.lua;;";
init_by_lua_file D:/openresty-1.21.4.1-win64/zhongkui-waf-master/init.lua;
init_worker_by_lua_file D:/openresty-1.21.4.1-win64/zhongkui-waf-master/init_worker.lua;
access_by_lua_file D:/openresty-1.21.4.1-win64/zhongkui-waf-master/waf.lua;
body_filter_by_lua_file D:/openresty-1.21.4.1-win64/zhongkui-waf-master/body_filter.lua;
header_filter_by_lua_file D:/openresty-1.21.4.1-win64/zhongkui-waf-master/header_filter.lua;
但是在修改完nginx.conf之后就无法运行nginx了，如果没有做此修改的话，nginx可以正常运行，请问是我的配置出现问题了吗？
求一个解决方案，谢谢！

**Comment by bukaleyang** [comment]
看一下nginx日志，logs/error.log，里面一定有错误信息。

**Comment by zzkzkkzzkk** [comment]
好的，这个问题我已经解决了，谢谢！

**Comment by bukaleyang** [comment]
> 好的，这个问题我已经解决了，谢谢！

ok，使用过程中如果遇到问题欢迎提交Issue或pr。
