### ISSUE TITLE
基于Openresty使用本项目时，需要保证使用较新版本（lib/resty/redis.lua版本需要在0.30及以上）

### ISSUE THREAD

**Issue by LeeZBug** [bukaleyang/zhongkui-waf#16]
0.29及之前的lib/resty/redis.lua不包含函数register_module_prefix，会导致使用本项目时报错。

**Comment by bukaleyang** [comment]
是这样，最少要0.30吧，所以你可以升级到最新版本，或者注释掉redisCli.lua中redis.register_module_prefix("bf")这一行。
