### ISSUE TITLE
lib/cc.lua:3: module 'table.nkeys' not found:

### ISSUE THREAD

**Issue by ZTzha** [bukaleyang/zhongkui-waf#18]
这个怎么破

**Comment by bukaleyang** [comment]
你用的OpenResty还是Nginx？升级下你的OpenResty看看。

**Comment by ZTzha** [comment]
用nginx，我写了一个计算table长度的方法替换掉nkeys，可以通过test了

**Comment by bukaleyang** [comment]
nginx的话，建议用OpenResty版本的LuaJIT，nkeys函数可以被LuaJIT编译，效率会更高点。

**Comment by ZTzha** [comment]
这个支持http2的吗
