### ISSUE TITLE
redis主机字段填写域名报错

### ISSUE THREAD

**Issue by lip215591601** [bukaleyang/zhongkui-waf#19]
![image](https://github.com/bukaleyang/zhongkui-waf/assets/140064899/1178d41d-6700-4a92-b0c2-83b00aaef6a5)

**Comment by bukaleyang** [comment]
换成ip看看，这里原则上是要配置ip地址的。

**Comment by lip215591601** [comment]
换成ip地址后没有问题

**Comment by bukaleyang** [comment]
或者你在nginx配置文件中配置下  resolver 8.8.8.8;

**Comment by bukaleyang** [comment]
配置redis域名访问的话，要在nginx配置文件中配置下 resolver 8.8.8.8;

**Comment by lip215591601** [comment]
好的
