### ISSUE TITLE
user-agent列表新增建议

### ISSUE THREAD

**Issue by fengguowudi** [bukaleyang/zhongkui-waf#2]
https://support.censys.io/hc/en-us/articles/360043177092-from-faq
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/bad-user-agents.list

**Comment by bukaleyang** [comment]
感谢建议，有时间会更新一下。

**Comment by bukaleyang** [comment]
已更新
