### ISSUE TITLE
ipBlackList无效，geoip解析失败

### ISSUE THREAD

**Issue by ZTzha** [bukaleyang/zhongkui-waf#29]
geoip解析失败，libmaxminddb已安装，geoip地址库已下载并能正常解析（使用php）
[lua] geoip.lua:30: lookup(): failed to lookup by ip,reason:lookup failed: Name or service not known, client: 212.30.61.132,

whiteIP = "off",ip白名单已关闭（是否有影响？）
blackIP = "on", ip黑名单已开启
rules/ipBlackList 和 config.lua内配置ipBlackList，均失效，无法拦截。

**Comment by ZTzha** [comment]
local ip = ipUtils.getClientIP()

**Comment by bukaleyang** [comment]
GeoLite2-City.mmdb这个文件下载了吗？你用的哪个版本？最新版本的配置文件已经不是config.lua了，下载最新版本试试
