### ISSUE TITLE
請問是否post 也不支援http v2 ?

### ISSUE THREAD

**Issue by chiyouli** [bukaleyang/zhongkui-waf#32]
將nginx 設定改成http2後ｐｏｓｔ出現錯誤，錯誤資訊如下

2023/11/20 11:52:45 [error] 3795#0: *67 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/conf/zhongkui-waf/lib/lib.lua:500: http v2 not supported yet
stack traceback:
coroutine 0:
        [C]: in function 'socket'
        /usr/local/openresty/nginx/conf/zhongkui-waf/lib/lib.lua:500: in function 'isEvilReqBody'

**Comment by bukaleyang** [comment]
lua-nginx-module应该是支持http2的，你使用的是nginx还是openresty？编译的时候是否有加上--with-http_v2_module选项？

**Comment by chiyouli** [comment]
使用的是openresty
版本是 1.21.4.3

configure時有加上--with-http_v2_module

**Comment by bukaleyang** [comment]
nginx的配置文件中是否正确配置，比如 listen 443 ssl http2;

**Comment by chiyouli** [comment]
有喔~
listen 443 ssl http2;   這邊把http2拿掉就正常了, 加上http2時, 只有post 會報錯

**Comment by bukaleyang** [comment]
……之前没有测试过http2，看了下官方issues，确实是有些api不支持http2，读取post请求时候就用到了。

**Comment by chiyouli** [comment]
了解~
請問會預計升級改寫以支援http2嗎?

**Comment by bukaleyang** [comment]
会，但不会很快，最近比较忙。

**Comment by bukaleyang** [comment]
已经支援http2了，不知道你是否有再测试？
