### ISSUE TITLE
证书管理，请求异常

### ISSUE THREAD

**Issue by lchuanqi** [bukaleyang/zhongkui-waf#36]
Web-UI 中的证书管理，显示“请求异常，错误提示：error”。Nginx 错误日志显示：

2024/03/07 11:24:10 [error] 26341#26341: *16 lua entry thread aborted: runtime error: /usr/local/openresty/zhongkui-waf/admin/lua/certificate.lua:11: module
 'openssl.x509' not found:	no field package.preload['openssl.x509']
	no file '/usr/local/openresty/zhongkui-waf/openssl/x509.lua'
	no file '/usr/local/openresty/zhongkui-waf/lib/openssl/x509.lua'
	no file '/usr/local/openresty/zhongkui-waf/admin/lua/openssl/x509.lua'
	no file '/usr/local/openresty/site/lualib/openssl/x509.ljbc'
	no file '/usr/local/openresty/site/lualib/openssl/x509/init.ljbc'
	no file '/usr/local/openresty/lualib/openssl/x509.ljbc'
	no file '/usr/local/openresty/lualib/openssl/x509/init.ljbc'
	no file '/usr/local/openresty/site/lualib/openssl/x509.lua'
	no file '/usr/local/openresty/site/lualib/openssl/x509/init.lua'
	no file '/usr/local/openresty/lualib/openssl/x509.lua'
	no file '/usr/local/openresty/lualib/openssl/x509/init.lua'
	no file './openssl/x509.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1/openssl/x509.lua'
	no file '/usr/local/share/lua/5.1/openssl/x509.lua'
	no file '/usr/local/share/lua/5.1/openssl/x509/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/openssl/x509.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/openssl/x509/init.lua'
	no file '/usr/local/openresty/site/lualib/openssl/x509.so'
	no file '/usr/local/openresty/lualib/openssl/x509.so'
	no file './openssl/x509.so'
	no file '/usr/local/lib/lua/5.1/openssl/x509.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/openssl/x509.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no module 'openssl.x509' in file '/usr/local/lib/lua/5.1/openssl.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/usr/local/openresty/zhongkui-waf/admin/lua/certificate.lua:11: in main chunk, client: 10.255.110.220, server: localhost, request: "GET /certificate
/list?page=1&limit=10 HTTP/1.1", host: "10.255.200.87:1226", referrer: "http://10.255.200.87:1226/view/common/certificate.html"

这似乎是说缺少一些lua包，请问如何安装呢？

**Comment by bukaleyang** [comment]
需要安装luaossl库
https://github.com/bukaleyang/zhongkui-waf?tab=readme-ov-file#luaossl%E5%BA%93
或者install.sh里有

**Comment by lchuanqi** [comment]
在编译 luaossl时，有报错：

--2024-03-07 12:07:15--  https://github.com/wahern/luaossl/archive/refs/tags/rel-20220711.tar.gz
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/wahern/luaossl/tar.gz/refs/tags/rel-20220711 [following]
--2024-03-07 12:07:15--  https://codeload.github.com/wahern/luaossl/tar.gz/refs/tags/rel-20220711
Resolving codeload.github.com (codeload.github.com)... 20.205.243.165
Connecting to codeload.github.com (codeload.github.com)|20.205.243.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/usr/local/src/luaossl-rel-20220711.tar.gz’

    [   <=>                                                                                                             ] 505,174     1.12MB/s   in 0.4s   

2024-03-07 12:07:17 (1.12 MB/s) - ‘/usr/local/src/luaossl-rel-20220711.tar.gz’ saved [505174]

cp /usr/local/src/luaossl-rel-20220711/config.h.guess /usr/local/src/luaossl-rel-20220711/config.h
cp /usr/local/src/luaossl-rel-20220711/config.h /usr/local/src/luaossl-rel-20220711/src/config.h
mkdir -p /usr/local/src/luaossl-rel-20220711/src/5.1
cc -O2 -std=gnu99 -fPIC -g -Wall -Wextra  -Wno-missing-field-initializers  -Wno-override-init -Wno-unused   -D_REENTRANT -D_THREAD_SAFE -D_GNU_SOURCE  -DHAV
E_CONFIG_H -DCOMPAT53_PREFIX=luaossl -c -o /usr/local/src/luaossl-rel-20220711/src/5.1/openssl.o /usr/local/src/luaossl-rel-20220711/src/openssl.c/usr/local/src/luaossl-rel-20220711/src/openssl.c:85:17: fatal error: lua.h: No such file or directory
 #include <lua.h>
                 ^
compilation terminated.
make: *** [/usr/local/src/luaossl-rel-20220711/src/5.1/openssl.o] Error 1
[luaossl安装成功]

**Comment by bukaleyang** [comment]
cd /usr/local/src
if [ ! -x "lua-5.1.5.tar.gz" ]; then
    wget https://lua.org/ftp/lua-5.1.5.tar.gz
fi
tar -zxf lua-5.1.5.tar.gz
cd ./lua-5.1.5
make linux test

**Comment by lchuanqi** [comment]
> cd /usr/local/src if [ ! -x "lua-5.1.5.tar.gz" ]; then wget https://lua.org/ftp/lua-5.1.5.tar.gz fi tar -zxf lua-5.1.5.tar.gz cd ./lua-5.1.5 make linux test


编译lua-5.1.5 是正常的。
使用Centos7执行的install.sh 脚本，只有编译luaossl-rel-20220711 有上面的错误，其他步骤没有问题。
