### ISSUE TITLE
openresty-1.21.4.1报了个错

### ISSUE THREAD

**Issue by tts2** [bukaleyang/zhongkui-waf#4]
报错信息如下:
C:\JAVAProject\A1Project\openresty-1.21.4.1>nginx.exe -c C:/JAVAProject/A1Projec
t/nginxWebUI/nginx.conf -p C:/JAVAProject/A1Project/openresty-1.21.4.1/
nginx: [error] init_by_lua_file error: ...ect/A1Project/openresty-1.21.4.1/zhong
kui-waf/lib/ip.lua:148: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...ect/A1Project/openresty-1.21.4.1/zhongkui-waf/lib/ip.lua:148: in func
tion 'mergeAndSort'
        ...oject/A1Project/openresty-1.21.4.1/zhongkui-waf/init.lua:43: in main
chunk
配置信息如下:
events { 
	accept_mutex on; 
	multi_accept on; 
  }
http {
  include mime.types;
  keepalive_timeout 75s;
  gzip on;
  gzip_min_length 1k;
  gzip_comp_level 6;
  client_max_body_size 1024m;
  client_header_buffer_size 32k;
  client_body_buffer_size 8m;
  server_names_hash_bucket_size 512;
  proxy_headers_hash_max_size 51200;
  proxy_headers_hash_bucket_size 6400;
  gzip_types application/javascript application/x-javascript text/javascript text/css application/json application/xml;
  lua_shared_dict dict_cclimit 10m;
  lua_shared_dict dict_accesstoken 10m;
  lua_shared_dict dict_blackip 10m;
  lua_shared_dict dict_locks 100k;
  lua_shared_dict dict_config 5m;
  lua_shared_dict dict_config_rules_hits 5m;
  lua_shared_dict dict_req_count 5m;
  lua_package_path "C:/JAVAProject/A1Project/openresty-1.21.4.1/zhongkui-waf/?.lua;C:/JAVAProject/A1Project/openresty-1.21.4.1/zhongkui-waf/lib/?.lua;;";
  init_by_lua_file C:/JAVAProject/A1Project/openresty-1.21.4.1/zhongkui-waf/init.lua;
  init_worker_by_lua_file C:/JAVAProject/A1Project/openresty-1.21.4.1/zhongkui-waf/init_worker.lua;
  access_by_lua_file C:/JAVAProject/A1Project/openresty-1.21.4.1/zhongkui-waf/waf.lua;
  body_filter_by_lua_file C:/JAVAProject/A1Project/openresty-1.21.4.1/zhongkui-waf/body_filter.lua;
  header_filter_by_lua_file C:/JAVAProject/A1Project/openresty-1.21.4.1/zhongkui-waf/header_filter.lua;
  log_by_lua_file C:/JAVAProject/A1Project/openresty-1.21.4.1/zhongkui-waf/dashboard/count_traffic.lua;
  include C:/JAVAProject/A1Project/nginxWebUI/conf.d/all.conf;
}

**Comment by bukaleyang** [comment]
你可能是没有修改rulePath配置，这个配置项在config.lua文件中，修改为C:/JAVAProject/A1Project/openresty-1.21.4.1/zhongkui-waf/rules/。同时redirect_html、dashboard_html可能也要做响应修改。

**Comment by tts2** [comment]
解决了,还要配置zhongkui-waf/config.lua

**Comment by tts2** [comment]
谢谢
