### ISSUE TITLE
登录钟馗的过程nginx的error.log记录到许多有关lookup():的错误，这个是什么原因导致的？

### ISSUE THREAD

**Issue by Lijuming33** [bukaleyang/zhongkui-waf#40]
2024/05/22 11:20:06 [notice] 423991#423991: signal process started
2024/05/22 11:20:18 [error] 423992#423992: *19 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:1226"
2024/05/22 11:20:33 [error] 423992#423992: *19 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "POST /user/login HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/login"
2024/05/22 11:20:34 [error] 423992#423992: *19 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /admin/css/loader.css HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /admin/css/admin.css HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/admin.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/message.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/yaml.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/tab.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/menu.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/frame.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/convert.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/fullscreen.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/drawer.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/loading.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /config/pear.config.yml HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /admin/data/menu.json?fresh=0.01277277687763756 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/index.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/echarts.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/view/dashboard.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /component/pear/module/echartsTheme.js?v=3.40.0 HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/view/dashboard.html"
2024/05/22 11:20:34 [error] 423992#423992: *20 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /admin/data/world.json HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/view/dashboard.html"
2024/05/22 11:20:34 [error] 423992#423992: *19 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /admin/data/china.json HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/view/dashboard.html"
2024/05/22 11:20:34 [error] 423992#423992: *19 [lua] geoip.lua:51: lookup(): failed to lookup by ip,reason:not found, client: 127.0.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", host: "127.0.0.1:1226", referrer: "http://127.0.0.1:1226/view/dashboard.html"

**Comment by Lijuming33** [comment]
已经安装了GeoIP
(base) w@XiaoXin-15-Air:/usr/local/openresty/nginx/zhongkui$ ls /usr/local/share/GeoIP/
GeoLite2-ASN.mmdb  GeoLite2-City.mmdb  GeoLite2-Country.mmdb
(base) w@XiaoXin-15-Air:/usr/local/openresty/nginx/zhongkui$

**Comment by bukaleyang** [comment]
已经修复，更新到最新版
