### ISSUE TITLE
mysql配置没有生效

### ISSUE THREAD

**Issue by freegit9527** [bukaleyang/zhongkui-waf#43]
你好，i请问对mysql版本有没有要求？安装的mysql5.5配置没有生效

**Comment by bukaleyang** [comment]
看下有没有错误日志，数据库要自己创建

**Comment by freegit9527** [comment]
数据库创建了，报错如下：

2024/05/30 08:20:14 [error] 54576#0: *111945 [lua] mysqlCli.lua:58: query(): bad result: Invalid default value for 'create_time': 1067: 42000., context: ngx.timer
2024/05/30 08:20:14 [error] 54576#0: *111945 [lua] sql.lua:206: failed to create table waf_status nil, context: ngx.timer
2024/05/30 08:20:14 [error] 54576#0: *111945 [lua] mysqlCli.lua:58: query(): bad result: Invalid default value for 'create_time': 1067: 42000., context: ngx.timer
2024/05/30 08:20:14 [error] 54576#0: *111945 [lua] sql.lua:206: failed to create table traffic_stats nil, context: ngx.timer
2024/05/30 08:20:14 [error] 54576#0: *111945 [lua] mysqlCli.lua:58: query(): bad result: Invalid default value for 'create_time': 1067: 42000., context: ngx.timer
2024/05/30 08:20:14 [error] 54576#0: *111945 [lua] sql.lua:206: failed to create table attack_log nil, context: ngx.timer
2024/05/30 08:20:14 [error] 54576#0: *111945 [lua] mysqlCli.lua:58: query(): bad result: Invalid default value for 'create_time': 1067: 42000., context: ngx.timer
2024/05/30 08:20:14 [error] 54576#0: *111945 [lua] sql.lua:206: failed to create table ip_block_log nil, context: ngx.timer

**Comment by bukaleyang** [comment]
你这是5.5以下版本吗？建议你升级到至少5.6以上

**Comment by freegit9527** [comment]
是版本问题，升级解决，另外建议attack_log表中的request_uri和ip建议增加长度，不然容易有报错；
ALTER TABLE attack_log MODIFY request_uri VARCHAR(500)；
ALTER TABLE attack_log MODIFY ip VARCHAR(128)；
![Uploading error.png…]()
