### ISSUE TITLE
Request body checking is enabled，http2 requests are not supported without content-length header。

### ISSUE THREAD

**Issue by zhuquehxb** [bukaleyang/zhongkui-waf#45]
Log：
`2024/06/01 07:32:57 [error] 29161#0: *57521 lua entry thread aborted: runtime error: /usr/local/openresty/zhongkui-waf/lib/request.lua:47: http2 requests are not supported without content-length header
stack traceback:
coroutine 0:
[C]: in function ＇read_body＇
/usr/local/openresty/zhongkui-waf/lib/request.lua:47: in function ＇getRequestBody＇
/usr/local/openresty/zhongkui-waf/lib/lib.lua:569: in function ＇isEvilReqBody＇
/usr/local/openresty/zhongkui-waf/waf.lua:49: in main chunk, client: 111.35.211.10, server: bing.com, request: ＂GET /jobs.html HTTP/2.0＂, host: ＂www.bing.com＂`

Add "content-length" to what file and code? Please fix the code.

**Comment by bukaleyang** [comment]
需要openresty官方支持。
