### ISSUE TITLE
添加了ip白名单，访问页面都变成了下载

### ISSUE THREAD

**Issue by wlintian** [bukaleyang/zhongkui-waf#46]
![image](https://github.com/bukaleyang/zhongkui-waf/assets/101079612/d964b1b1-fca4-4556-8d57-2a8878d0adf3)

**Comment by bukaleyang** [comment]
感谢反馈，已修复，重新下载最新的看看。或者你手动修改lib/action.lua 143行改为ngx.status = ngx.OK
https://github.com/bukaleyang/zhongkui-waf/commit/39c88463c8534014b18c09c647f41e4ca18cfdb7
