### ISSUE TITLE
没有拦截到?

### ISSUE THREAD

**Issue by tts2** [bukaleyang/zhongkui-waf#5]
log:
220.196.160.61 - - [12/May/2023:16:48:18 +0800] "GET /zhongkui/dashboard HTTP/1.1" 301 175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
59.83.208.105 - - [12/May/2023:16:48:18 +0800] "\x16\x03\x01\x01\x08\x01\x00\x01\x04\x03\x03G`JuN\xEE\xED" 400 163 "-" "-"
122.14.46.232 - - [12/May/2023:16:51:39 +0800] "GET /zhongkui/dashboard HTTP/2.0" 500 585 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
中间那种可以拦截么?

**Comment by bukaleyang** [comment]
这种拦截不了，nginx直接报400错误，都进不了防火墙识别环节，但也许可以在写日志阶段做些处理。
