### ISSUE TITLE
1.3版本貌似不支持mysql8.4

### ISSUE THREAD

**Issue by zhuquehxb** [bukaleyang/zhongkui-waf#52]
安装waf启动nginx，没有在数据库中自动生成表结构，看日志发现是waf代码与mysql8.4的兼容性存在问题
`2024/08/17 22:56:38 [error] 339936#0: *3635 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/mysql.lua:929: auth plugin caching_sha2_password or sha256_password are not supported because resty.rsa is not installed
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/openresty/lualib/resty/mysql.lua:895: in function '_encrypt_password'
	/usr/local/openresty/lualib/resty/mysql.lua:929: in function '_write_encode_password'
	/usr/local/openresty/lualib/resty/mysql.lua:1072: in function '_handle_auth_result'
	/usr/local/openresty/lualib/resty/mysql.lua:1212: in function 'connect'
	/usr/local/openresty/zhongkui-waf/lib/mysql_cli.lua:27: in function 'get_connection'
	/usr/local/openresty/zhongkui-waf/lib/mysql_cli.lua:48: in function 'query'
	/usr/local/openresty/zhongkui-waf/lib/sql.lua:298: in function </usr/local/openresty/zhongkui-waf/lib/sql.lua:277>, context: ngx.timer`

**Comment by bukaleyang** [comment]
已修复

**Comment by wy3552128** [comment]
> 已修复
添加了/lib/resty/rsa.lua，提示这个错误
`2024/08/18 17:13:34 [error] 68914#0: *5 lua entry thread aborted: runtime error: /usr/local/openresty/zhongkui-waf/lib/resty/rsa.lua:391: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2: undefined symbol: EVP_PKEY_size
stack traceback:
coroutine 0:
	[C]: in function '__index'
	/usr/local/openresty/zhongkui-waf/lib/resty/rsa.lua:391: in function 'new'
	/usr/local/openresty/lualib/resty/mysql.lua:909: in function '_encrypt_password'
	/usr/local/openresty/lualib/resty/mysql.lua:929: in function '_write_encode_password'
	/usr/local/openresty/lualib/resty/mysql.lua:1072: in function '_handle_auth_result'
	/usr/local/openresty/lualib/resty/mysql.lua:1212: in function 'connect'
	/usr/local/openresty/zhongkui-waf/lib/mysql_cli.lua:27: in function 'get_connection'
	/usr/local/openresty/zhongkui-waf/lib/mysql_cli.lua:48: in function 'query'
	/usr/local/openresty/zhongkui-waf/lib/sql.lua:204: in function </usr/local/openresty/zhongkui-waf/lib/sql.lua:188>, context: ngx.timer`

**Comment by bukaleyang** [comment]
要安装OpenSSL，如果还是不行，删掉这个文件，然后修改你mysql用户的加密插件
ALTER USER 'your_username'@'your_host' IDENTIFIED WITH mysql_native_password BY 'your_password';  
FLUSH PRIVILEGES;
