### ISSUE TITLE
对于编码绕过有什么好的解决办法

### ISSUE THREAD

**Issue by BLkubin** [bukaleyang/zhongkui-waf#7]
作者你好，
对于编码绕过有什么好的解决办法？例如url编码，Unicode编码等。

**Comment by bukaleyang** [comment]
目前仅做了uri的解码，其他请求部分的解码还有待完善，见 ./lib/decoder.lua文件。至于方法，难点可能是要对payload编码格式先做识别再解码，识别起来有难度，或者也可以直接暴力解码，能解出来就算解码成功，对payload做至多两次的解码。

**Comment by tts2** [comment]
openrasp可以一起上

**Comment by tts2** [comment]
openrasp我是装在tomcat上的

**Comment by BLkubin** [comment]
感谢，我明白了
